title: I'm learning to GitHub
theme: minima
author: Tiiiim
email: timothee.thiry@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a newbie in web developpement. Looking forward to learn awesome stuff.

# social links
twitter_username: I-don't-tweet # DO NOT include the @ character, or else the build will fail!
github_username:  timotheethiry # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
